version: "3.8"

services:
  django:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: django
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:8000 --workers 3
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - static_volume:/app/static

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - certs:/etc/letsencrypt
      - static_volume:/app/static
    depends_on:
      - django

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'while true; do certbot renew --quiet && sleep 12h; done'"

volumes:
  certs:
  static_volume:
