
services:
  web:
    build: .
    container_name: django_api
    env_file: .env
    command: gunicorn --workers=4 --threads=4 --timeout=60 --bind 0.0.0.0:8000 myproject.wsgi:application
    expose:
      - "8000"
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=*

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
